// TEMPORARY DATA

const product = [
  {
    id: 1,
    name: "product Adidas T-Shirt",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["gray", "products/1.jpg", "products/2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    price: 99.99,
    images: [
      "products/1.jpg",
      "products/2.jpg",
      "products/3.jpg",
      "products/4.jpg",
      "products/5.jpg",
    ],
    attributes: [
      { name: "color", value: "gray" },
      { name: "size", value: "M" },
      { name: "material", value: "Cotton" },
    ],
  },
  {
    id: 2,
    name: "Puma Ultra Zoom Waffle",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["green", "black", "products/6.jpg", "products/7.jpg"],
    sizes: ["38", "39", "40", "41", "42"],
    price: 120.00,
    images: [
      "products/6.jpg",
      "products/7.jpg",
      "products/8.jpg",
    ],
    attributes: [
      { name: "color", value: "black" },
      { name: "size", value: "41" },
      { name: "material", value: "Synthetic" },
    ],
  },
  {
    id: 3,
    name: "Nike Air Max 270",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["blue", "white", "products/9.jpg", "products/10.jpg"],
    sizes: ["38", "39", "40", "41", "42"],
    price: 150.00,
    images: [
      "products/9.jpg",
      "products/10.jpg",
      "products/11.jpg",
    ],
    attributes: [
      { name: "color", value: "white" },
      { name: "size", value: "40" },
      { name: "material", value: "Mesh" },
    ],
  },
  {
    id: 4,
    name: "Calvin Klein Sweater",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["brown", "products/12.jpg"],
    sizes: ["S", "M", "L", "XL"],
    price: 75.00,
    images: [
      "products/12.jpg",
      "products/13.jpg",
    ],
    attributes: [
      { name: "color", value: "brown" },
      { name: "size", value: "L" },
      { name: "material", value: "Wool" },
    ],
  },
  {
    id: 5,
    name: "Levis Jeans",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["dark-blue", "products/14.jpg"],
    sizes: ["28", "30", "32", "34", "36"],
    price: 60.00,
    images: [
      "products/14.jpg",
      "products/15.jpg",
    ],
    attributes: [
      { name: "color", value: "dark-blue" },
      { name: "size", value: "32" },
      { name: "material", value: "Denim" },
    ],
  },
  {
    id: 6,
    name: "New Balance 990v5",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["grey", "products/16.jpg"],
    sizes: ["38", "39", "40", "41", "42"],
    price: 175.00,
    images: [
      "products/16.jpg",
      "products/17.jpg",
    ],
    attributes: [
      { name: "color", value: "grey" },
      { name: "size", value: "42" },
      { name: "material", value: "Suede" },
    ],
  },
  {
    id: 7,
    name: "Ralph Lauren Polo",
    short_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    colors: ["red", "products/18.jpg"],
    sizes: ["S", "M", "L", "XL"],
    price: 55.00,
    images: [
      "products/18.jpg",
      "products/19.jpg",
    ],
    attributes: [
      { name: "color", value: "red" },
      { name: "size", value: "S" },
      { name: "material", value: "Pique" },
    ],
  },
];
